// ScreenHome moved to src/features/home/ in Phase 2 Step 8.
// ScreenMemory moved to src/features/memory/ in Phase 2 Step 8.
// ScreenChat moved to src/features/chat/ in Phase 2 Step 5.
// ScreenWork moved to src/features/work/ in Phase 2 Step 7.
// ScreenCapture moved to src/features/capture/ in Phase 2 Step 7.
// ScreenIntegrations moved to src/features/integrations/ in Phase 2 Step 7.
// ScreenSettings moved to src/features/settings-screen/ in Phase 2 Step 7.
// ScreenAgents moved to src/features/agents/ in Phase 2 Step 6.
// ScreenMeetings moved to src/features/meetings/ in Phase 2 Step 9.
// ScreenMemoryDebug moved to src/features/memory-debug/ in Phase 2 Step 4.
// ScreenMorningBrief moved to src/features/morning-brief/ in Phase 2 Step 3.
// SettingsModal moved to src/features/settings/ in Phase 2 Step 10.
