// Mock IPC transport + ensureRuntimeDeps extracted from App.tsx (Phase 2 Step 11)
import { handleMockCommand } from "@/shared/ipc/mock/handler";

/** Fallback when `ipc-client.js` is absent — delegates to shared mock handler. */
export function mockIpcInvoke(command: string, payload: any): any {
  try {
    const data = handleMockCommand(command, payload);
    return { ok: true, data };
  } catch (error: any) {
    return {
      ok: false,
      error: {
        code: error?.code || "IPC_ERROR",
        message: error?.message || "Unknown IPC error",
        details: error?.details ?? null,
      },
    };
  }
}

export function ensureRuntimeDeps(): void {
  const w = window as any;
  if (!w.ShogunIpcClient) {
    w.ShogunIpcClient = {
      createIpcClient: () => ({
        transport: 'mock',
        invoke: async (command: string, payload: any) => mockIpcInvoke(command, payload),
      }),
    };
  }
  if (!w.ShogunAPI) {
    w.ShogunAPI = {
      createApi: (client: any) => ({
        appOpenHummingbird: (input: any) => client.invoke('app_open_hummingbird', input),
        appCreateShareLink: (input: any) => client.invoke('app_create_share_link', input),
        settingsLoad: (input: any) => client.invoke('app_settings_load', input),
        settingsSave: (input: any) => client.invoke('app_settings_save', input),
        settingsExport: (input: any) => client.invoke('app_settings_export', input || {}),
        settingsImport: (input: any) => client.invoke('app_settings_import', input || {}),
        deadLetterList: (input: any) => client.invoke('shogun_dead_letter_list', input || {}),
        deadLetterRetry: (input: any) => client.invoke('shogun_dead_letter_retry', input || {}),
        deadLetterClear: (input: any) => client.invoke('shogun_dead_letter_clear', input || {}),
        deadLetterRetryOne: (input: any) => client.invoke('shogun_dead_letter_retry_one', input || {}),
        deadLetterDelete: (input: any) => client.invoke('shogun_dead_letter_delete', input || {}),
        integrationConnect: (input: any) => client.invoke('app_integration_connect', input),
        oauthGoogleStart: (input: any) => client.invoke('shogun_oauth_google_start', input),
        agentRunNow: (input: any) => client.invoke('shogun_agent_run_now', input),
        integrationImportCredentials: (input: any) =>
          client.invoke('app_integration_import_credentials', input),
        integrationCredentialsStatus: (input: any) =>
          client.invoke('app_integration_credentials_status', input),
        integrationToggle: (input: any) => client.invoke('app_integration_toggle', input),
        googleCalendarSync: (input: any) => client.invoke('shogun_google_calendar_sync', input),
        gmailSync: (input: any) => client.invoke('shogun_gmail_sync', input),
        slackSync: (input: any) => client.invoke('shogun_slack_sync', input),
        notionSync: (input: any) => client.invoke('shogun_notion_sync', input),
        githubSync: (input: any) => client.invoke('shogun_github_sync', input),
        linearSync: (input: any) => client.invoke('shogun_linear_sync', input),
        driveSync: (input: any) => client.invoke('shogun_drive_sync', input),
        zoomSync: (input: any) => client.invoke('shogun_zoom_sync', input),
        capturePause: (input: any) => client.invoke('app_capture_pause', input),
        captureResume: (input: any) => client.invoke('app_capture_resume', input),
        permissionsManage: (input: any) => client.invoke('app_permissions_manage', input),
        privacyPickApp: (input: any) => client.invoke('app_privacy_pick_app', input || {}),
        diagnosticsReport: (input: any) => client.invoke('app_diagnostics_report', input),
        updatesCheck: (input: any) => client.invoke('app_updates_check', input),
        updatesDownloadInstall: (input: any) => client.invoke('app_updates_download_install', input),
        frontendErrorReport: (input: any) => client.invoke('app_frontend_error_report', input),
        accountDeleteData: (input: any) => client.invoke('app_delete_data_range', input),
        accountDeleteAll: (input: any) => client.invoke('app_delete_all_data', input),
        accountDeleteSelf: (input: any) => client.invoke('app_delete_account', input),
        memorySearch: (input: any) => client.invoke('shogun_memory_search', input),
        memoryFetch: (input: any) => client.invoke('shogun_memory_fetch', input),
        memoryIngest: (input: any) => client.invoke('shogun_memory_ingest', input),
        aiFieldList: (input: any) => client.invoke('shogun_ai_field_list', input || {}),
        aiFieldUpsert: (input: any) => client.invoke('shogun_ai_field_upsert', input),
        contextActionList: (input: any) => client.invoke('shogun_context_action_list', input || {}),
        contextActionAuditList: (input: any) => client.invoke('shogun_context_action_audit_list', input),
        contextActionPropose: (input: any) => client.invoke('shogun_context_action_propose', input),
        contextActionSetStatus: (input: any) => client.invoke('shogun_context_action_set_status', input),
        contextActionExecute: (input: any) => client.invoke('shogun_context_action_execute', input),
        scheduleQueueList: (input: any) => client.invoke('shogun_schedule_queue_list', input || {}),
        crmUpdateQueueList: (input: any) => client.invoke('shogun_crm_update_queue_list', input || {}),
        scheduleQueueRemove: (input: any) => client.invoke('shogun_schedule_queue_remove', input),
        crmUpdateQueueRemove: (input: any) => client.invoke('shogun_crm_update_queue_remove', input),
        scheduleQueueRetry: (input: any) => client.invoke('shogun_schedule_queue_retry', input),
        crmUpdateQueueRetry: (input: any) => client.invoke('shogun_crm_update_queue_retry', input),
        memoryDelete: (input: any) => client.invoke('shogun_memory_delete', input),
        memorySummaryGet: (input: any) => client.invoke('shogun_memory_summary_get', input),
        memorySummaryBatch: (input: any) => client.invoke('shogun_memory_summary_batch', input),
        memorySummaryInvalidate: (input: any) => client.invoke('shogun_memory_summary_invalidate', input),
        memoryEmbedBackfill: (input: any) =>
          client.invoke('shogun_memory_embed_backfill', input, { timeoutMs: 600000 }),
        memoryEmbedBackfillCancel: (input: any) =>
          client.invoke('shogun_memory_embed_backfill_cancel', input || {}),
        entityQuery: (input: any) => client.invoke('shogun_entity_query', input),
        entityContextGet: (input: any) => client.invoke('shogun_entity_context_get', input),
        contextSearch: (input: any) => client.invoke('shogun_context_search', input),
        contextRecentGet: (input: any) => client.invoke('shogun_context_recent_get', input || {}),
        contextTasksList: (input: any) => client.invoke('shogun_context_tasks_list', input || {}),
        briefGet: (input: any) => client.invoke('shogun_brief_get', input),
        openPack: (input: any) => client.invoke('shogun_open_pack', input),
        startFocusSession: (input: any) => client.invoke('shogun_start_focus_session', input),
        draftReply: (input: any) => client.invoke('shogun_draft_reply', input),
        chatComplete: (input: any) => client.invoke('shogun_chat_complete', input),
        statsGet: (input: any) => client.invoke('shogun_stats', input),
        draftCreate: (input: any) => client.invoke('shogun_draft', input),
        llmApiKeySet: (input: any) => client.invoke('app_llm_api_key_set', input),
        llmApiKeyStatus: (input: any) => client.invoke('app_llm_api_key_status', input),
        llmApiKeyClear: (input: any) => client.invoke('app_llm_api_key_clear', input),
        scheduleAction: (input: any) => client.invoke('shogun_schedule_action', input),
        meetingStart: (input: any) => client.invoke('shogun_meeting_start', input),
        meetingLinkClientNote: (input: any) => client.invoke('shogun_meeting_link_client_note', input),
        meetingResolveByStorageKey: (input: any) =>
          client.invoke('shogun_meeting_resolve_by_storage_key', input),
        meetingStop: (input: any) => client.invoke('shogun_meeting_stop', input),
        meetingNoteAppendBlock: (input: any) => client.invoke('shogun_meeting_note_append_block', input),
        meetingNoteEditBlock: (input: any) => client.invoke('shogun_meeting_note_edit_block', input),
        meetingNoteDeleteBlock: (input: any) => client.invoke('shogun_meeting_note_delete_block', input),
        meetingEnhance: (input: any) => client.invoke('shogun_meeting_enhance', input),
        meetingReEnhance: (input: any) => client.invoke('shogun_meeting_re_enhance', input),
        meetingTranscriptForBlock: (input: any) => client.invoke('shogun_meeting_transcript_for_block', input),
        meetingTranscriptLive: (input: any) => client.invoke('shogun_meeting_transcript_live', input),
        meetingPurge: (input: any) => client.invoke('shogun_meeting_purge', input),
        meetingList: (input: any) => client.invoke('shogun_meeting_list', input),
        meetingGet: (input: any) => client.invoke('shogun_meeting_get', input),
        meetingTranscriptGet: (input: any) => client.invoke('shogun_meeting_transcript_get', input),
        meetingNotesGet: (input: any) => client.invoke('shogun_meeting_notes_get', input),
        meetingsSearch: (input: any) => client.invoke('shogun_meetings_search', input),
        meetingRecipeRun: (input: any) => client.invoke('shogun_meeting_recipe_run', input),
        meetingTemplatesList: (input: any) => client.invoke('shogun_meeting_templates_list', input),
        meetingTranscriptPush: (input: any) => client.invoke('shogun_meeting_transcript_push', input),
        meetingAudioStatus: (input: any) => client.invoke('shogun_meeting_audio_status', input),
        meetingMicStart: (input: any) => client.invoke('shogun_meeting_mic_start', input),
        meetingMicStop: (input: any) => client.invoke('shogun_meeting_mic_stop', input),
        meetingTranscribePcm: (input: any) => client.invoke('shogun_meeting_transcribe_pcm', input),
        meetingMcpTools: (input: any) => client.invoke('shogun_meeting_mcp_tools', input),
        meetingImportPick: (input: any) => client.invoke('shogun_meeting_import_pick', input || {}),
        meetingImportFile: (input: any) => client.invoke('shogun_meeting_import_file', input),
        meetingContextTimeline: (input: any) => client.invoke('shogun_meeting_context_timeline', input),
        appNavigate: (input: any) => client.invoke('app_navigate', input),
      }),
    };
  }
  if (!w.ShogunActionRegistry) {
    w.ShogunActionRegistry = {
      createActionRegistry: (api: any) => {
        const map: Record<string, any> = {
          'app.open_hummingbird': api.appOpenHummingbird,
          'app.create_share_link': api.appCreateShareLink,
          'settings.save': api.settingsSave,
          'settings.load': api.settingsLoad,
          'settings.export': api.settingsExport,
          'settings.import': api.settingsImport,
          'dead_letter.list': api.deadLetterList,
          'dead_letter.retry': api.deadLetterRetry,
          'dead_letter.clear': api.deadLetterClear,
          'dead_letter.retry_one': api.deadLetterRetryOne,
          'dead_letter.delete': api.deadLetterDelete,
          'integrations.connect': api.integrationConnect,
          'oauth.google.start': api.oauthGoogleStart,
          'agent.run_now': api.agentRunNow,
          'integrations.import_credentials': api.integrationImportCredentials,
          'integrations.credentials_status': api.integrationCredentialsStatus,
          'integrations.toggle': api.integrationToggle,
          'calendar.sync': api.googleCalendarSync,
          'gmail.sync': api.gmailSync,
          'slack.sync': api.slackSync,
          'notion.sync': api.notionSync,
          'github.sync': api.githubSync,
          'linear.sync': api.linearSync,
          'drive.sync': api.driveSync,
          'zoom.sync': api.zoomSync,
          'capture.pause': api.capturePause,
          'capture.resume': api.captureResume,
          'permissions.manage': api.permissionsManage,
          'privacy.pick_app': api.privacyPickApp,
          'diagnostics.report': api.diagnosticsReport,
          'updates.check': api.updatesCheck,
          'updates.download_install': api.updatesDownloadInstall,
          'data.delete_range': api.accountDeleteData,
          'data.delete_all': api.accountDeleteAll,
          'account.delete': api.accountDeleteSelf,
          'memory.search': api.memorySearch,
          'ai_field.list': api.aiFieldList,
          'ai_field.upsert': api.aiFieldUpsert,
          'action.list': api.contextActionList,
          'action.audit_list': api.contextActionAuditList,
          'action.propose': api.contextActionPropose,
          'action.set_status': api.contextActionSetStatus,
          'action.execute': api.contextActionExecute,
          'queue.tasks.list': api.scheduleQueueList,
          'queue.crm_updates.list': api.crmUpdateQueueList,
          'queue.tasks.remove': api.scheduleQueueRemove,
          'queue.crm_updates.remove': api.crmUpdateQueueRemove,
          'queue.tasks.retry': api.scheduleQueueRetry,
          'queue.crm_updates.retry': api.crmUpdateQueueRetry,
          'memory.fetch': api.memoryFetch,
          'memory.ingest': api.memoryIngest,
          'memory.delete': api.memoryDelete,
          'memory.embed_backfill': api.memoryEmbedBackfill,
          'memory.embed_backfill_cancel': api.memoryEmbedBackfillCancel,
          'memory.summary.get': api.memorySummaryGet,
          'memory.summary.batch': api.memorySummaryBatch,
          'memory.summary.invalidate': api.memorySummaryInvalidate,
          'entity.query': api.entityQuery,
          'entity.context.get': api.entityContextGet,
          'context.search': api.contextSearch,
          'context.recent.get': api.contextRecentGet,
          'context.tasks.list': api.contextTasksList,
          'brief.get': api.briefGet,
          'chat.complete': api.chatComplete,
          'llm.save_api_key': api.llmApiKeySet,
          'llm.api_key_status': api.llmApiKeyStatus,
          'llm.clear_api_key': api.llmApiKeyClear,
          'shogun.open_pack': api.openPack,
          'shogun.start_focus_session': api.startFocusSession,
          'shogun.draft_reply': api.draftReply,
          'stats.get': api.statsGet,
          'app.navigate': api.appNavigate,
          'draft.create': api.draftCreate,
          'schedule.create': api.scheduleAction,
          'meetings.start': api.meetingStart,
          'meetings.link_client_note': api.meetingLinkClientNote,
          'meetings.resolve_by_storage_key': api.meetingResolveByStorageKey,
          'meetings.stop': api.meetingStop,
          'meetings.note.append_block': api.meetingNoteAppendBlock,
          'meetings.note.edit_block': api.meetingNoteEditBlock,
          'meetings.note.delete_block': api.meetingNoteDeleteBlock,
          'meetings.enhance': api.meetingEnhance,
          'meetings.re_enhance': api.meetingReEnhance,
          'meetings.transcript.for_block': api.meetingTranscriptForBlock,
          'meetings.transcript.live': api.meetingTranscriptLive,
          'meetings.purge': api.meetingPurge,
          'meetings.list': api.meetingList,
          'meetings.get': api.meetingGet,
          'meetings.transcript.get': api.meetingTranscriptGet,
          'meetings.notes.get': api.meetingNotesGet,
          'meetings.search': api.meetingsSearch,
          'meetings.recipe.run': api.meetingRecipeRun,
          'meetings.templates.list': api.meetingTemplatesList,
          'meetings.transcript.push': api.meetingTranscriptPush,
          'meetings.audio.status': api.meetingAudioStatus,
          'meetings.mic.start': api.meetingMicStart,
          'meetings.mic.stop': api.meetingMicStop,
          'meetings.transcribe.pcm': api.meetingTranscribePcm,
          'meetings.mcp.tools': api.meetingMcpTools,
          'meetings.import.pick': api.meetingImportPick,
          'meetings.import.file': api.meetingImportFile,
          'meetings.context_timeline': api.meetingContextTimeline,
        };
        return {
          run: async (key: string, payload: any) => {
            const fn = map[key];
            if (!fn) return { ok:false, error:{ message:`Action not connected: ${key}` } };
            const result = await fn(payload || {});
            return result && result.ok === false ? result : { ok:true, data:result };
          },
        };
      },
    };
  }
}
